package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author rxtsel
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaceGrafica
     */
    public Interfaz() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/assets/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        ID1 = new javax.swing.JLabel();
        ID_TEXT = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JLabel();
        NOMBRE_TEXT = new javax.swing.JTextField();
        TIPO_CUERPO_AGUA = new javax.swing.JLabel();
        TIPO_CUERPO_AGUA_TEXT = new javax.swing.JTextField();
        MUNICIPIO = new javax.swing.JLabel();
        MUNICIPIO_TEXT = new javax.swing.JTextField();
        IRCA = new javax.swing.JLabel();
        IRCA_TEXT = new javax.swing.JTextField();
        TIPO_AGUA = new javax.swing.JLabel();
        TIPO_AGUA_TEXT = new javax.swing.JTextField();
        BTN_INGRESAR = new javax.swing.JButton();
        BTN_PROCESAR = new javax.swing.JButton();
        ENTRADAS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ENTRADAS_TXT_AREA = new javax.swing.JTextArea();
        SALIDAS = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SALIDAS_TXT_AREA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_LIMPIAR = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_EDITAR = new javax.swing.JButton();
        BTN_CONSULTAR = new javax.swing.JButton();
        SEARCH_TEXT = new javax.swing.JTextField();
        BTN_SEARCH = new javax.swing.JButton();

        jScrollPane3.setViewportView(jEditorPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lector de calidad de agua by @rxtsel");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(70, 20));
        setName("frame"); // NOI18N
        setResizable(false);

        ID1.setLabelFor(ID1);
        ID1.setText("ID*");

        ID_TEXT.setNextFocusableComponent(NOMBRE_TEXT);
        ID_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TEXTActionPerformed(evt);
            }
        });

        NOMBRE.setText("NOMBRE*");

        NOMBRE_TEXT.setNextFocusableComponent(MUNICIPIO_TEXT);
        NOMBRE_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBRE_TEXTActionPerformed(evt);
            }
        });

        TIPO_CUERPO_AGUA.setText("TIPO CUERPO DE AGUA*");

        TIPO_CUERPO_AGUA_TEXT.setNextFocusableComponent(TIPO_AGUA_TEXT);
        TIPO_CUERPO_AGUA_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPO_CUERPO_AGUA_TEXTActionPerformed(evt);
            }
        });

        MUNICIPIO.setText("MUNICIPIO*");

        MUNICIPIO_TEXT.setNextFocusableComponent(TIPO_CUERPO_AGUA_TEXT);
        MUNICIPIO_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUNICIPIO_TEXTActionPerformed(evt);
            }
        });

        IRCA.setText("IRCA*");

        IRCA_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRCA_TEXTActionPerformed(evt);
            }
        });

        TIPO_AGUA.setText("TIPO DE AGUA*");

        TIPO_AGUA_TEXT.setNextFocusableComponent(IRCA_TEXT);
        TIPO_AGUA_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPO_AGUA_TEXTActionPerformed(evt);
            }
        });

        BTN_INGRESAR.setText("Ingresar");
        BTN_INGRESAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_INGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_INGRESARActionPerformed(evt);
            }
        });

        BTN_PROCESAR.setText("Procesar");
        BTN_PROCESAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_PROCESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PROCESARActionPerformed(evt);
            }
        });

        ENTRADAS.setLabelFor(ID1);
        ENTRADAS.setText("Entradas");

        ENTRADAS_TXT_AREA.setColumns(20);
        ENTRADAS_TXT_AREA.setRows(5);
        jScrollPane1.setViewportView(ENTRADAS_TXT_AREA);

        SALIDAS.setLabelFor(ID1);
        SALIDAS.setText("Salidas");

        SALIDAS_TXT_AREA.setColumns(20);
        SALIDAS_TXT_AREA.setRows(5);
        jScrollPane2.setViewportView(SALIDAS_TXT_AREA);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LECTOR DE CALIDAD DE AGUA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Made with ❤️ by @rxtsel");

        BTN_LIMPIAR.setText("Limpiar");
        BTN_LIMPIAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMPIARActionPerformed(evt);
            }
        });

        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });

        BTN_EDITAR.setText("Guardar");
        BTN_EDITAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDITARActionPerformed(evt);
            }
        });

        BTN_CONSULTAR.setText("Consultar");
        BTN_CONSULTAR.setMaximumSize(new java.awt.Dimension(80, 22));
        BTN_CONSULTAR.setMinimumSize(new java.awt.Dimension(70, 20));
        BTN_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONSULTARActionPerformed(evt);
            }
        });

        SEARCH_TEXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SEARCH_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_TEXTActionPerformed(evt);
            }
        });

        BTN_SEARCH.setBackground(new java.awt.Color(29, 29, 29));
        BTN_SEARCH.setForeground(new java.awt.Color(245, 245, 245));
        BTN_SEARCH.setText("BUSCAR");
        BTN_SEARCH.setBorder(null);
        BTN_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SEARCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IRCA_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IRCA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TIPO_AGUA_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIPO_AGUA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TIPO_CUERPO_AGUA_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TIPO_CUERPO_AGUA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MUNICIPIO_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MUNICIPIO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NOMBRE_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ID_TEXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ENTRADAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(73, 73, 73))
                            .addComponent(SALIDAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BTN_INGRESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BTN_PROCESAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_LIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BTN_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BTN_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BTN_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(SEARCH_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BTN_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEARCH_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ENTRADAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ID_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(NOMBRE_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(MUNICIPIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(MUNICIPIO_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(TIPO_CUERPO_AGUA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(TIPO_CUERPO_AGUA_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(TIPO_AGUA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(TIPO_AGUA_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(IRCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(IRCA_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(SALIDAS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_INGRESAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_PROCESAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_LIMPIAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_CONSULTAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_EDITAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ELIMINAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        ID_TEXT.getAccessibleContext().setAccessibleName("");
        ID_TEXT.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TEXTActionPerformed

    private void NOMBRE_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBRE_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBRE_TEXTActionPerformed

    private void TIPO_CUERPO_AGUA_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPO_CUERPO_AGUA_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPO_CUERPO_AGUA_TEXTActionPerformed

    private void MUNICIPIO_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUNICIPIO_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MUNICIPIO_TEXTActionPerformed

    private void IRCA_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRCA_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IRCA_TEXTActionPerformed

    private void TIPO_AGUA_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPO_AGUA_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPO_AGUA_TEXTActionPerformed

    private void BTN_INGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_INGRESARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_INGRESARActionPerformed

    private void BTN_PROCESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PROCESARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_PROCESARActionPerformed

    private void BTN_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMPIARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_LIMPIARActionPerformed

    private void BTN_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONSULTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CONSULTARActionPerformed

    private void BTN_EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDITARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EDITARActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void SEARCH_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCH_TEXTActionPerformed

    private void BTN_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_SEARCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_CONSULTAR;
    public javax.swing.JButton BTN_EDITAR;
    public javax.swing.JButton BTN_ELIMINAR;
    public javax.swing.JButton BTN_INGRESAR;
    public javax.swing.JButton BTN_LIMPIAR;
    public javax.swing.JButton BTN_PROCESAR;
    public javax.swing.JButton BTN_SEARCH;
    public javax.swing.JLabel ENTRADAS;
    public javax.swing.JTextArea ENTRADAS_TXT_AREA;
    public javax.swing.JLabel ID1;
    public javax.swing.JTextField ID_TEXT;
    public javax.swing.JLabel IRCA;
    public javax.swing.JTextField IRCA_TEXT;
    public javax.swing.JLabel MUNICIPIO;
    public javax.swing.JTextField MUNICIPIO_TEXT;
    public javax.swing.JLabel NOMBRE;
    public javax.swing.JTextField NOMBRE_TEXT;
    public javax.swing.JLabel SALIDAS;
    public javax.swing.JTextArea SALIDAS_TXT_AREA;
    public javax.swing.JTextField SEARCH_TEXT;
    public javax.swing.JLabel TIPO_AGUA;
    public javax.swing.JTextField TIPO_AGUA_TEXT;
    public javax.swing.JLabel TIPO_CUERPO_AGUA;
    public javax.swing.JTextField TIPO_CUERPO_AGUA_TEXT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
